catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from catalog.apps import CatalogConfig
from catalog.views import (
    ProductListView,
    ProductDetailView,
    ProductCreateView,
    ProductUpdateView,
    ProductDeleteView,
)

app_name = CatalogConfig.name

urlpatterns = [
    path("", ProductListView.as_view(), name="base"),
    path("catalog/<int:pk>/", ProductDetailView.as_view(), name="products"),
    path('catalog/<int:pk>/list/', ProductListView.as_view(), name='product_list'),
    path('catalog/<int:pk>/detail/', cache_page(60)(ProductDetailView.as_view()),
         name='product_detail'),
    path("catalog/create", ProductCreateView.as_view(), name="product_create"),
    path(
        "catalog/<int:pk>/update/", ProductUpdateView.as_view(), name="product_update"
    ),
    path(
        "catalog/<int:pk>/delete/", ProductDeleteView.as_view(), name="product_delete"
    ),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path("admin/", admin.site.urls),
                  path("", include("catalog.urls", namespace="catalog")),
                  path("items/", include("items.urls", namespace="items")),
                  path("users/", include("users.urls", namespace="users")),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

items/urls.py
from django.urls import path

from items.apps import ItemsConfig
from items.views import ItemListView, ItemDetailView, ItemCreateView, ItemUpdateView, ItemDeleteView

app_name = ItemsConfig.name

urlpatterns = [
    path('', ItemListView.as_view(), name='blogpost_list'),
    path('blog/<slug:slug>/', ItemDetailView.as_view(), name='blogpost_detail'),
    path('create/', ItemCreateView.as_view(), name='blogpost_form'),
    path('blog/<int:pk>/update/', ItemUpdateView.as_view(), name='blogpost_update'),
    path('blog/<int:pk>/delete/', ItemDeleteView.as_view(), name='blogpost_delete'),
]

catalog/models.py
from django.db import models

from users.models import User


class Category(models.Model):
    name = models.CharField(
        max_length=100,
        verbose_name="Наименование",
    )
    description = models.TextField(
        verbose_name="Описание",
    )

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"

        def __str__(self):
            return self.name


class Product(models.Model):
    name = models.CharField(
        max_length=100,
        verbose_name="Наименование",
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="products",
    )

    description = models.TextField(
        verbose_name="Описание",
    )
    photo = models.ImageField(
        upload_to="product/photo",
        verbose_name="Фото",
    )
    category = models.CharField(
        max_length=50,
        verbose_name="Категория",
    )

    price = models.IntegerField(
        verbose_name="Цена за покупку",
    )
    created_at = models.DateField(
        verbose_name="Дата создания (БД)",
    )
    update_at = models.DateField(
        verbose_name="Дата последнего изменения",
    )
    owner = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        verbose_name="Владелец",
        related_name="products",
        blank=True,
        null=True,
    )
    is_published = models.BooleanField(
        default=False, verbose_name="Опубликовано", help_text="Опубликовать продукт"
    )

    def __str__(self):
        return f"{self.name}: {self.price_for_buy} руб."

    class Meta:
        verbose_name = "Продукт"
        verbose_name_plural = "Продукты"
        permissions = [
            ("can_delite_product", "Can delite product"),
            ("can_change_category", "Can change category"),
            ("can_description_product", "Can description product"),
        ]

        def __str__(self):
            return self.name


class Version(models.Model):
    product = models.ForeignKey(
        Product,
        related_name="versions",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        verbose_name="Продукт",
    )
    version_number = models.CharField(
        max_length=10,
        verbose_name="Номер версии",
        help_text="Введите номер версии",
        null=True,
        blank=True,
    )
    version_name = models.CharField(
        max_length=100,
        verbose_name="Название версии",
        help_text="Введите название версии",
        null=True,
        blank=True,
    )
    is_version_active = models.BooleanField(
        default=False,
        verbose_name="Активная версия",
        help_text="Является ли версия активной",
    )

    class Meta:
        verbose_name = "Версия"
        verbose_name_plural = "Версии"
        ordering = ["version_number", "version_name"]

    def __str__(self):
        return self.version_name

catalog/forms.py
from django.forms import ModelForm, forms, BooleanField

from catalog.models import Product, Version


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, BooleanField):
                field.widget.attrs["class"] = "form-check-input"
            else:
                field.widget.attrs["class"] = "form-control"


class ProductForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Product
        fields = "__all__"

    forbidden_words = [
        "казино",
        "криптовалюта",
        "крипта",
        "биржа",
        "дешево",
        "бесплатно",
        "обман",
        "полиция",
        "радар",
    ]

    def clean_name(self):
        cleaned_data = self.cleaned_data["name"]

        for word in self.forbidden_words:
            if word in cleaned_data.lower():
                raise forms.ValidationError(
                    "Извините, но в названии продукта запрещены недопустимые слова."
                )
        return cleaned_data

    def clean_description(self):
        cleaned_data = self.cleaned_data["description"]

        for word in self.forbidden_words:
            if word in cleaned_data.lower():
                raise forms.ValidationError(
                    "Извините, но в описании продукта запрещены недопустимые слова."
                )
        return cleaned_data


class VersionForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Version
        fields = "__all__"


class ProductModeratorForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Product
        fields = ('name', 'description')

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.forms import inlineformset_factory
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, UpdateView, CreateView, DeleteView

from catalog.forms import ProductForm, VersionForm, ProductModeratorForm
from catalog.models import Product, Version, Category
from catalog.services import get_categories_from_cache


class ProductListView(LoginRequiredMixin, ListView):
    model = Product


class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Product

    def get_queryset(self):
        return get_categories_from_cache()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        ProductFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            context['formset'] = ProductFormset(self.request.POST, instance=self.object)
        else:
            context['formset'] = ProductFormset(instance=self.object)
        return context

    def form_valid(self, form):
        formset = self.get_context_data()["formset"]
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()
        return super().form_valid(form)


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy("catalog:product_list")

    def form_valid(self, form):
        product = form.save(commit=False)
        product.owner = self.request.user
        product.save()
        return redirect("catalog:product_detail", product.pk)


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy("catalog:product_list")

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        ProductFormset = inlineformset_factory(Product, Version, VersionForm, extra=1)
        if self.request.method == "POST":
            context_data["formset"] = ProductFormset(
                self.request.POST, instance=self.object
            )
        else:
            context_data["formset"] = ProductFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        context = self.get_context_data()
        formset = context['formset']
        if form.is_valid() and formset.is_valid():
            self.object = form.save()
            formset.instance = self.object
            formset.save()
            return super().form_valid(form)
        else:
            return self.render_to_response(self.get_context_data(form=form, formset=formset))

    def get_form_class(self):

        user = self.request.user
        if user == self.object.owner:
            return ProductForm
        if user.has_perm(["can_delite_product", "can_change_category",
                          "can_description_product"]):
            return ProductModeratorForm
        raise PermissionDenied


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    model = Product
    success_url = reverse_lazy("catalog:product_list")

    def get_form_class(self):
        user = self.request.user
        if user == self.object.owner:
            return ProductForm
        raise PermissionDenied


class CategoryListView(ListView):
    model = Category

    def get_queryset(self):
        return get_categories_from_cache()

catalog/templates/catalog/base.html
{% load static %}
<!doctype html>
<html data-bs-theme="auto" lang="en">
<head>
    <script src="{% static 'js/color-modes.js' %}"></script>

    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1" name="viewport">
    <meta content="" name="description">
    <meta content="Mark Otto, Jacob Thornton, and Bootstrap contributors" name="author">
    <meta content="Hugo 0.122.0" name="generator">
    <title>Album example · Bootstrap v5.3</title>

    <link href="https://getbootstrap.com/docs/5.3/examples/album/" rel="canonical">


    <link href="https://cdn.jsdelivr.net/npm/@docsearch/css@3" rel="stylesheet">

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Favicons -->
    <link href="/docs/5.3/assets/img/favicons/apple-touch-icon.png" rel="apple-touch-icon"
          sizes="180x180">
    <link href="/docs/5.3/assets/img/favicons/favicon-32x32.png" rel="icon" sizes="32x32"
          type="image/png">
    <link href="/docs/5.3/assets/img/favicons/favicon-16x16.png" rel="icon" sizes="16x16"
          type="image/png">
    <link href="/docs/5.3/assets/img/favicons/manifest.json" rel="manifest">
    <link color="#712cf9" href="/docs/5.3/assets/img/favicons/safari-pinned-tab.svg" rel="mask-icon">
    <link href="/docs/5.3/assets/img/favicons/favicon.ico" rel="icon">
    <meta content="#712cf9" name="theme-color">


    <style>
        .bd-placeholder-img {
          font-size: 1.125rem;
          text-anchor: middle;
          -webkit-user-select: none;
          -moz-user-select: none;
          user-select: none;
        }

        @media (min-width: 768px) {
          .bd-placeholder-img-lg {
            font-size: 3.5rem;
          }
        }

        .b-example-divider {
          width: 100%;
          height: 3rem;
          background-color: rgba(0, 0, 0, .1);
          border: solid rgba(0, 0, 0, .15);
          border-width: 1px 0;
          box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
        }

        .b-example-vr {
          flex-shrink: 0;
          width: 1.5rem;
          height: 100vh;
        }

        .bi {
          vertical-align: -.125em;
          fill: currentColor;
        }

        .nav-scroller {
          position: relative;
          z-index: 2;
          height: 2.75rem;
          overflow-y: hidden;
        }

        .nav-scroller .nav {
          display: flex;
          flex-wrap: nowrap;
          padding-bottom: 1rem;
          margin-top: -1px;
          overflow-x: auto;
          text-align: center;
          white-space: nowrap;
          -webkit-overflow-scrolling: touch;
        }

        .btn-bd-primary {
          --bd-violet-bg: #712cf9;
          --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

          --bs-btn-font-weight: 600;
          --bs-btn-color: var(--bs-white);
          --bs-btn-bg: var(--bd-violet-bg);
          --bs-btn-border-color: var(--bd-violet-bg);
          --bs-btn-hover-color: var(--bs-white);
          --bs-btn-hover-bg: #6528e0;
          --bs-btn-hover-border-color: #6528e0;
          --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
          --bs-btn-active-color: var(--bs-btn-hover-color);
          --bs-btn-active-bg: #5a23c8;
          --bs-btn-active-border-color: #5a23c8;
        }

        .bd-mode-toggle {
          z-index: 1500;
        }

        .bd-mode-toggle .dropdown-menu .active .bi {
          display: block !important;
        }
    </style>


</head>
<body>
<svg class="d-none" xmlns="http://www.w3.org/2000/svg">
    <symbol id="check2" viewBox="0 0 16 16">
        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
    </symbol>
    <symbol id="circle-half" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"/>
    </symbol>
    <symbol id="moon-stars-fill" viewBox="0 0 16 16">
        <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>
        <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/>
    </symbol>
    <symbol id="sun-fill" viewBox="0 0 16 16">
        <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
    </symbol>
</svg>

<div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
    <button aria-expanded="false"
            aria-label="Toggle theme (auto)"
            class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center"
            data-bs-toggle="dropdown"
            id="bd-theme"
            type="button">
        <svg class="bi my-1 theme-icon-active" height="1em" width="1em">
            <use href="#circle-half"></use>
        </svg>
        <span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
    </button>
    <ul aria-labelledby="bd-theme-text" class="dropdown-menu dropdown-menu-end shadow">
        <li>
            <button aria-pressed="false" class="dropdown-item d-flex align-items-center"
                    data-bs-theme-value="light" type="button">
                <svg class="bi me-2 opacity-50" height="1em" width="1em">
                    <use href="#sun-fill"></use>
                </svg>
                Light
                <svg class="bi ms-auto d-none" height="1em" width="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
        <li>
            <button aria-pressed="false" class="dropdown-item d-flex align-items-center"
                    data-bs-theme-value="dark" type="button">
                <svg class="bi me-2 opacity-50" height="1em" width="1em">
                    <use href="#moon-stars-fill"></use>
                </svg>
                Dark
                <svg class="bi ms-auto d-none" height="1em" width="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
        <li>
            <button aria-pressed="true" class="dropdown-item d-flex align-items-center active"
                    data-bs-theme-value="auto" type="button">
                <svg class="bi me-2 opacity-50" height="1em" width="1em">
                    <use href="#circle-half"></use>
                </svg>
                Auto
                <svg class="bi ms-auto d-none" height="1em" width="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
    </ul>
</div>


<header data-bs-theme="dark">
    {% include 'includes/inc_menu.html' %}
</header>

<main>

    <section class="py-5 text-center container">
        <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto">
                <h1 class="fw-light">Маркет</h1>
                <p class="lead text-body-secondary">Электроника</p>
                <p>
                    <a class="btn btn-primary my-2" href="#">Main call to action</a>
                    <a class="btn btn-secondary my-2" href="#">Secondary action</a>
                </p>
            </div>
        </div>
    </section>


    {% block content %}
    {% endblock %}
</main>

<footer class="text-body-secondary py-5">
    <div class="container">
        <p class="float-end mb-1">
            <a href="#">Back to top</a>
        </p>
        <p class="mb-1">Album example is &copy; Bootstrap, but please download and customize it for
            yourself!</p>
        <p class="mb-0">New to Bootstrap? <a href="/">Visit the homepage</a> or read our <a
                href="/docs/5.3/getting-started/introduction/">getting started guide</a>.</p>
    </div>
</footer>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

</body>
</html>

catalog/templates/catalog/category.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        <div class="col">
            {% for object in object_list %}
            <div class="card shadow-sm">
                <img src="{{ product.photo | media_filter  }}>
                    <div class="card-body">
                <p class="card-text">Название: {{object.name}}</p>
                <p class="card-text">Цена: {{object.price}}</p>
                <p class="card-text">Описание: {{object.description | truncatechars:101}}</p>
                <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <a class="btn btn-primary" href="{% url 'catalog:products'  object.pk %}"
                           role="button">Посмотреть
                        </a>
                    </div>
                    <small class="text-body-secondary"></small>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            <div class="col">
                <div class="card shadow-sm">
                    <img card-body src="{{ product.photo | media_filter  }}>
                    <div class="">
                    <p class="card-text">{{ object.name}}</p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <button class="btn btn-sm btn-outline-secondary" type="button">
                                View
                            </button>
                            <button class="btn btn-sm btn-outline-secondary" type="button">
                                Edit
                            </button>
                        </div>
                        <small class="text-body-secondary">9 mins</small>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="container">
    <form class="row" enctype="multipart/form-data" method="post">
        <div class="col-6">
            <div class="card shadow-sm">
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p %}
                </div>
                <button class="btn btn-primary" type="submit">
                    {% if object %}
                    Сохранить
                    {% else %}
                    Создать
                    {% endif %}
                </button>
            </div>
        </div>
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    {{formset.management_form }}
                    {% for form in formset.forms %}
                    {{ form.as_p }}
                    {% endfor %}
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            <div class="col">
                <div class="card shadow-sm">
                    <img card-body src="{{ product.photo | media_filter  }}">
                    <div class="">
                    <p class="card-text">{{ object.name}}</p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            {% if
                            perms.product_can_delete_product and
                            perms.product_can_change_category and
                            perms.product_can_description_product
                            %}
                            <button class="btn btn-sm btn-outline-secondary" type="button">
                                Редактировать
                            </button>
                            {% endif %}
                            <button class="btn btn-sm btn-outline-secondary" type="button">
                                Удалить
                            </button>
                            <button class="btn btn-sm btn-outline-secondary" type="button">
                                Просмотр
                            </button>
                        </div>
                        <small class="text-body-secondary"></small>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
</div>
{% endblock %}